<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;

use Carbon\Carbon;
use Spatie\Permission\Models\Role;

class RolesTableSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::statement('DELETE FROM roles');
		\DB::statement('ALTER TABLE roles AUTO_INCREMENT = 1;');
		\DB::table('roles')->insert([
			[
				'name'=>'superadmin',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'superadmin',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'baak',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'baak',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'programstudi',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'programstudi',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'pmb',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'pmb',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'keuangan',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'keuangan',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'perpustakaan',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'perpustakaan',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'lppm',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'lppm',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'puslahta',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'dosen',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'dosen',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'dosenwali',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'dosenwali',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'mahasiswa',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'mahasiswa',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'mahasiswabaru',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'mahasiswabaru',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'alumni',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'alumni',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'orangtuawali',
				'guard_name'=>'web',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
			[
				'name'=>'orangtuawali',
				'guard_name'=>'api',
				'created_at'=>Carbon::now(),
				'updated_at'=>Carbon::now()
			],
		]);
	}
}